# Generated by Django 4.1.3 on 2022-11-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=100)),
                ("gmail", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("userID", models.CharField(max_length=50)),
                ("timecreated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productID", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=300)),
                ("detail", models.CharField(max_length=500)),
                ("type", models.CharField(max_length=100)),
                ("amount", models.IntegerField(max_length=100)),
                ("timecreated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
