# Generated by Django 4.1.3 on 2022-11-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
