# Generated by Django 4.1.3 on 2022-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_product_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(default="default", max_length=200),
        ),
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(default="default", max_length=200),
        ),
    ]
