# Generated by Django 4.1.3 on 2022-11-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_account_password_account_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="gmail",
            new_name="email",
        ),
    ]
